### ISSUE TITLE
Domain Removal Request

### ISSUE THREAD

**Issue by inferenceus** [r3g-5z/abusive-content-hosts-blocklist#4]
Hello,

I have been informed that my domain has been added to your publicly available blocklist due to apparent harrassment from me, which is completely false. While I have had discussions with people about this, including a trustworthy source who provided screeenshots of harrassment towards you, I, personally, have no been involved in this, and people who have been involved in it can attest to my innocence regarding this matter.

While I don't mind if you would like to block my domain for personal reasons, it's untrue that I have been involved in any harrassment towards you, and there is clear evidence to support my claim of innocence, so I would like the record to be set straight.

Thank you for understanding.

**Comment by r3g-5z** [comment]
You're still in association with these bad actors including using their services and making suspicious false claims about their activities.

Until you drop all association and communication with these people for blatant harassment towards me, it's not being removed.

**Comment by r3g-5z** [comment]
I'm getting very tired of this persistent annoyance with you people and if you're in any way associated with them, it's going to be your issue as well until you drop all communication and involvement with them. Yes you probably are not the one apart of the harassment, but you are still in close contact with them despite extremely obvious evidence of KiwiFarms-like behaviour to me.

If this does not stop, everyone associated is going to be receiving abuse complaints to your ISPs. If you don't want that, then cut ties with these obvious malicious trolls.

**Comment by r3g-5z** [comment]
It's also extremely suspicious that you claim that the "staff" at the website of this targeted harassment towards me have "dealt" with the bad actors when I can go on the front page and find what you said to be completely false. If you're trying to cover up for them, it's not working and I'm having trouble assuming you're in good faith here unless you completely dissolve any association with them.

**Comment by r3g-5z** [comment]
If you decide to follow through with this, and I hope you do if you're actually "not involved",  you can contact me through Twitter or Matrix (if you really have to over Twitter).
